from __future__ import annotations

from datetime import datetime, timezone
from typing import Any
from uuid import UUID

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.core.config import settings
from app.core.database import AsyncSessionFactory
from app.core.queue import get_redis_settings
from app.models import Agent, ExecutionLog, PromptVersion, Session


async def _get_run_session(session: AsyncSession, session_id: UUID) -> Session | None:
    result = await session.execute(
        select(Session)
        .options(
            selectinload(Session.agent).selectinload(Agent.prompt_versions),
            selectinload(Session.agent).selectinload(Agent.tools),
        )
        .where(Session.id == session_id)
    )
    return result.scalar_one_or_none()


async def _get_next_step_sequence(session: AsyncSession, session_id: UUID) -> int:
    result = await session.execute(
        select(func.coalesce(func.max(ExecutionLog.step_sequence), 0)).where(ExecutionLog.session_id == session_id)
    )
    return int(result.scalar_one()) + 1


def _append_log(
    db_session: AsyncSession,
    session_id: UUID,
    step_sequence: int,
    role: str,
    content: str,
    tool_calls: dict[str, Any] | None = None,
) -> int:
    db_session.add(
        ExecutionLog(
            session_id=session_id,
            step_sequence=step_sequence,
            role=role,
            content=content,
            tool_calls=tool_calls,
        )
    )
    return step_sequence + 1


def _build_scaffold_response(agent: Agent, prompt: str) -> str:
    active_prompt = next((item for item in agent.prompt_versions if item.is_active), None)
    tool_names = [tool.name for tool in agent.tools]

    message_parts = [
        f"Queued run completed for agent '{agent.name}'.",
        f"Prompt received: {prompt}",
    ]

    if isinstance(active_prompt, PromptVersion):
        message_parts.append(f"Active prompt version: v{active_prompt.version_number}.")
    else:
        message_parts.append("No active prompt version is configured yet.")

    if tool_names:
        message_parts.append(f"Registered tools available for future execution: {', '.join(tool_names)}.")
    else:
        message_parts.append("No tools are assigned to this agent yet.")

    message_parts.append(
        "This response is generated by the ARQ worker scaffold. Replace this logic with the real orchestration loop."
    )
    return " ".join(message_parts)


async def _mark_run_failed(session_id: UUID, reason: str) -> None:
    async with AsyncSessionFactory() as db_session:
        run_session = await db_session.get(Session, session_id)
        if run_session is None:
            return

        next_step = await _get_next_step_sequence(db_session, session_id)
        run_session.status = "failed"
        run_session.end_time = datetime.now(timezone.utc)
        _append_log(
            db_session,
            session_id,
            next_step,
            "system",
            f"Run failed in background worker: {reason}",
        )
        await db_session.commit()


async def process_agent_run(_: dict[str, Any], session_id: str, prompt: str) -> dict[str, str]:
    run_id = UUID(session_id)

    try:
        async with AsyncSessionFactory() as db_session:
            run_session = await _get_run_session(db_session, run_id)
            if run_session is None:
                return {"session_id": session_id, "status": "missing"}

            if run_session.status == "completed":
                return {"session_id": session_id, "status": run_session.status}

            next_step = await _get_next_step_sequence(db_session, run_id)
            run_session.status = "running"
            next_step = _append_log(
                db_session,
                run_id,
                next_step,
                "system",
                f"Worker picked up run for agent '{run_session.agent.name}'.",
            )
            next_step = _append_log(
                db_session,
                run_id,
                next_step,
                "system",
                (
                    f"Agent configured with provider '{run_session.agent.model_provider}' "
                    f"and model '{run_session.agent.target_model}'."
                ),
            )
            _append_log(
                db_session,
                run_id,
                next_step,
                "assistant",
                _build_scaffold_response(run_session.agent, prompt),
            )
            run_session.status = "completed"
            run_session.end_time = datetime.now(timezone.utc)
            await db_session.commit()
    except Exception as exc:
        await _mark_run_failed(run_id, str(exc))
        raise

    return {"session_id": session_id, "status": "completed"}


class WorkerSettings:
    functions = [process_agent_run]
    redis_settings = get_redis_settings()
    queue_name = settings.ARQ_QUEUE_NAME
    max_jobs = settings.ARQ_MAX_JOBS